OD-254: Add report_to_sentry function to base_controller
This is being used from multiple controllers and is not
reachable by any of them, producing error logs like:

  2026-08-19 05:21:23 - NoMethodError - undefined method 'report_to_sentry' for an instance of Controller::DomesticController: