Disable Rubocop rule to prevent test failures
Running `rubocop -A` detects and corrects the following "offense":

  spec/shared_context/shared_send_heat_pump.rb:15:29: C: [Corrected] RSpec/VerifiedDoubleReference: Use a constant class reference for verified doubles. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/VerifiedDoubleReference)
      response = class_double("response")
                              ^^^^^^^^^^

However, the updated code (`response = class_double(response)`) does not work and causes 2 test failures with the error:
]
  ArgumentError: Module or String expected, got nil

So we want to stop rubocop from updating htis line of code, which can be done by adding this comment to the line.